<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ApplicationIcon>icon.ico</ApplicationIcon>
		<StartupObject />
	</PropertyGroup>

	<!-- Убираем лишние Service-файлы -->
	<ItemGroup>
		<Compile Remove="Services\**" />
		<EmbeddedResource Remove="Services\**" />
		<None Remove="Services\**" />
	</ItemGroup>

	<!-- Подключаем пакеты -->
	<ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.1.1" />
		<PackageReference Include="EPPlus" Version="6.2.15" />
		<PackageReference Include="Google.Apis.Admin.Directory.directory_v1" Version="1.70.0.3840" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0-preview.6.25358.103" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Telegram.Bot" Version="22.6.0" />
	</ItemGroup>

	<!-- Ресурсы -->
	<ItemGroup>
		<Compile Update="Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>

		<EmbeddedResource Update="Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<!-- Иконка -->
	<ItemGroup>
		<Content Include="icon.ico" />
	</ItemGroup>

	<!-- Файлы, которые должны копироваться в bin -->
	<ItemGroup>
		<None Update="Info.xlsx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="InfoDate.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="key.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="root.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="token.env">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="users.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="wmbot.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
