<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <None Remove="THLCТРДС.xlsx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    <PackageReference Include="Telegram.Bot" Version="17.0.0" />
    <PackageReference Include="Telegram.Bot.Extensions.Polling" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ТРДС.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
